### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by mishailovic** [llistochek/yandex-music-downloader#11]
При попытке скачать плейлист "Мне нравится" получаю ошибку:

```
Traceback (most recent call last):
  File "C:\Users\misha\Desktop\yandex-music-downloader-main\main.py", line 395, in <module>
    result_tracks = get_playlist(session, args.playlist_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\misha\Desktop\yandex-music-downloader-main\main.py", line 237, in get_playlist
    tracks = [t for t in tracks if t is not None]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\misha\Desktop\yandex-music-downloader-main\main.py", line 237, in <listcomp>
    tracks = [t for t in tracks if t is not None]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\misha\Desktop\yandex-music-downloader-main\main.py", line 112, in from_json
    album_data = data['albums'][0]
                 ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

У меня Python 3.11 если что.

**Comment by llistochek** [comment]
Скиньте ссылку на плейлист, который вы пытаетесь скачать. Если не хотите светить аккаунтом в issue, можете скинуть мне [на почту](mailto:me@llistochek.ru).
