### ISSUE TITLE
Не работает пример запуска из Readme 

### ISSUE THREAD

**Issue by MrChebur** [llistochek/yandex-music-downloader#14]
Windows 10, при запуске команды в cmd:
``` python
C:\Users\1>"E:\Scripts\yandex_music_downloader\Scripts\python.exe" "E:\Scripts\yandex_music_downloader\main.py" --session-id "ХХХХХХ" --url "https://music.yandex.ru/album/11644078/track/6705392" --log-level DEBUG
```
Выдаёт такую ошибку:
``` python
22:52:57 |DEBUG| Starting new HTTPS connection (1): music.yandex.ru:443
22:52:58 |DEBUG| https://music.yandex.ru:443 "GET /handlers/track.jsx?track=6705392&lang=ru HTTP/1.1" 400 5678
Traceback (most recent call last):
  File "E:\Scripts\yandex_music_downloader\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\1\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\1\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\1\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Scripts\yandex_music_downloader\main.py", line 447, in <module>
    result_tracks = [get_full_track_info(session, args.track_id)]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Scripts\yandex_music_downloader\main.py", line 227, in get_full_track_info
    return FullTrackInfo.from_json(resp.json())
                                   ^^^^^^^^^^^
  File "E:\Scripts\yandex_music_downloader\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MrChebur** [comment]
Очень странно, но теперь тоже самое - работает. 
Извините за беспокойство.
