### ISSUE TITLE
Проблема с загрузкой

### ISSUE THREAD

**Issue by daodaodaodaodao** [llistochek/yandex-music-downloader#23]
Приветствую! ловлю ошибку при скачивании треков, есть подозрение что т.к недавно стало возможным загружать собственные треки на площадку - они также присутствуют в целевом плейлисте, натыкаясь на них скрипт ловит ошибку.

```
Traceback (most recent call last):
  File "/home/sergey/yandex_music_downloader/yandex-music-downloader/main.py", line 498, in <module>
    result_tracks = get_playlist(cached_session, args.playlist_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/yandex_music_downloader/yandex-music-downloader/main.py", line 265, in get_playlist
    tracks = [t for t in tracks if t is not None]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/yandex_music_downloader/yandex-music-downloader/main.py", line 265, in <listcomp>
    tracks = [t for t in tracks if t is not None]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sergey/yandex_music_downloader/yandex-music-downloader/main.py", line 149, in from_json
    has_lyrics = data['lyricsInfo']['hasAvailableTextLyrics']
                 ~~~~^^^^^^^^^^^^^^
KeyError: 'lyricsInfo'
```

**Comment by llistochek** [comment]
Исправил, проверяйте. Если скрипт все равно крашится - скиньте мне ссылку на плейлист или вывод скрипта с флагом `--debug`

**Comment by llistochek** [comment]
Я проверил, плейлист скачивается корректно. Насчет ошибки 400 - открыл новую issue.
