### ISSUE TITLE
Ошибка при загрузке

### ISSUE THREAD

**Issue by Kapuster** [llistochek/yandex-music-downloader#63]
Приветствую, получаю ошибку при загрузке. Плейлист около 1000 песен, примерно после 10 скачанных песен ошибка

```
Traceback (most recent call last):
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 199, in _new_conn
    sock = connection.create_connection(
        (self._dns_host, self.port),
    ...<2 lines>...
        socket_options=self.socket_options,
    )
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\socket.py", line 975, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11002] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 490, in _make_request
    raise new_e
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
    ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 1095, in _validate_conn
    conn.connect()
    ~~~~~~~~~~~~^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
                       ~~~~~~~~~~~~~~^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connection.py", line 206, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000002C32A19F9D0>: Failed to resolve 's242vlx.storage.yandex.net' ([Errno 11002] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s242vlx.storage.yandex.net', port=443): Max retries exceeded with url: /get-mp3/c568a324e71aa649823afe854f09518d/00062449dc56d22a/rmusic/U2FsdGVkX19JUP2xOW9nQLSVwhpXxfx6cKp_2_OC0s8qpXSXKnp-Y1ZM900eCx5EU8u-mXffmq2eNuGW3IE-JKXSN6u1-ZsLnZIhEIeKohs/4032e49a7f38a1f91d8ae3fbf44177f0f8144fbb1b013852650be43e25ad979f/31667?track-id=412281 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002C32A19F9D0>: Failed to resolve 's242vlx.storage.yandex.net' ([Errno 11002] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Scripts\yandex-music-downloader.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\ymd\cli.py", line 274, in main
    core.download_track(
    ~~~~~~~~~~~~~~~~~~~^
        client=client,
        ^^^^^^^^^^^^^^
    ...<6 lines>...
        covers_cache=covers_cache,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\ymd\core.py", line 113, in download_track
    http_utils.download_file(client.session, url, target_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\ymd\http_utils.py", line 7, in download_file
    resp = session.get(url)
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Dmitriy\AppData\Local\Programs\Python\Python313\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s242vlx.storage.yandex.net', port=443): Max retries exceeded with url: /get-mp3/c568a324e71aa649823afe854f09518d/00062449dc56d22a/rmusic/U2FsdGVkX19JUP2xOW9nQLSVwhpXxfx6cKp_2_OC0s8qpXSXKnp-Y1ZM900eCx5EU8u-mXffmq2eNuGW3IE-JKXSN6u1-ZsLnZIhEIeKohs/4032e49a7f38a1f91d8ae3fbf44177f0f8144fbb1b013852650be43e25ad979f/31667?track-id=412281 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002C32A19F9D0>: Failed to resolve 's242vlx.storage.yandex.net' ([Errno 11002] getaddrinfo failed)"))
```

**Comment by Kapuster** [comment]
Браузер - firefox, win11

**Comment by llistochek** [comment]
Попробуйте передать флаг `--enable-ipv6`

**Comment by Kapuster** [comment]
Да, помогло, загрузка пошла дальше
