### ISSUE TITLE
После обновления не могу запустить приложение

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#71]
```
> 
root@omv:~# pip install git+https://github.com/llistochek/yandex-music-downloader
Collecting git+https://github.com/llistochek/yandex-music-downloader
  Cloning https://github.com/llistochek/yandex-music-downloader to /tmp/pip-req-build-tens50n6
  Running command git clone -q https://github.com/llistochek/yandex-music-downloader /tmp/pip-req-build-tens50n6
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: yandex-music in /usr/local/lib/python3.9/dist-packages (from yandex-music-downloader==3.0.0b0) (2.2.0)
Requirement already satisfied: eyed3 in /usr/local/lib/python3.9/dist-packages (from yandex-music-downloader==3.0.0b0) (0.9.7)
Requirement already satisfied: deprecation<3.0.0,>=2.1.0 in /usr/local/lib/python3.9/dist-packages (from eyed3->yandex-music-downloader==3.0.0b0) (2.1.0)
Requirement already satisfied: filetype<2.0.0,>=1.0.7 in /usr/local/lib/python3.9/dist-packages (from eyed3->yandex-music-downloader==3.0.0b0) (1.2.0)
Requirement already satisfied: coverage[toml]<6.0.0,>=5.3.1 in /usr/local/lib/python3.9/dist-packages (from eyed3->yandex-music-downloader==3.0.0b0) (5.5)
Requirement already satisfied: toml in /usr/local/lib/python3.9/dist-packages (from coverage[toml]<6.0.0,>=5.3.1->eyed3->yandex-music-downloader==3.0.0b0) (0.10.2)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from deprecation<3.0.0,>=2.1.0->eyed3->yandex-music-downloader==3.0.0b0) (20.9)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.0.0b0) (2.32.3)
Requirement already satisfied: aiofiles in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.0.0b0) (22.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.0.0b0) (3.10.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (1.4.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (2.3.5)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (6.0.5)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (23.1.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.9/dist-packages (from yarl<2.0,>=1.0->aiohttp->yandex-music->yandex-music-downloader==3.0.0b0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downloader==3.0.0b0) (2.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downloader==3.0.0b0) (3.3.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downloader==3.0.0b0) (2024.6.2)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downloader==3.0.0b0) (1.7.1)
root@omv:~# ^C
root@omv:~# yandex-music-downloader --help
Traceback (most recent call last):
  File "/usr/local/bin/yandex-music-downloader", line 5, in <module>
    from ymd.cli import main
  File "/usr/local/lib/python3.9/dist-packages/ymd/cli.py", line 15, in <module>
    from ymd import core
  File "/usr/local/lib/python3.9/dist-packages/ymd/core.py", line 18, in <module>
    def full_title(obj: YandexMusicObject) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

Версия питона

```
> 
root@omv:~# python3 --version
Python 3.9.2
root@omv:~#

```

Что нужно сделать что бы заработало?
Система Debian 11 (openmediavault)

**Comment by llistochek** [comment]
Исправлено в c7e121b3e59865aa15200691dbe333e7a4b88aa8
