### ISSUE TITLE
Ошибка после обновления

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#73]
Обновился до v3.2.0b0 . Теперь при запуске ошибка.

```
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> Last login: Sun Nov 17 18:19:19 2024 from 192.168.1.95
> root@omv:~# pip install git+https://github.com/llistochek/yandex-music-downloader
> Collecting git+https://github.com/llistochek/yandex-music-downloader
>   Cloning https://github.com/llistochek/yandex-music-downloader to /tmp/pip-req-build-8tt__l4k
>   Running command git clone -q https://github.com/llistochek/yandex-music-downloader /tmp/pip-req-build-8tt__l4k
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>     Preparing wheel metadata ... done
> Requirement already satisfied: mutagen in /usr/lib/python3/dist-packages (from yandex-music-downloader==3.2.0b0) (1.45.1)
> Requirement already satisfied: yandex-music in /usr/local/lib/python3.9/dist-packages (from yandex-music-downloader==3.2.0b0) (2.2.0)
> Requirement already satisfied: aiohttp in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.2.0b0) (3.10.1)
> Requirement already satisfied: aiofiles in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.2.0b0) (22.1.0)
> Requirement already satisfied: requests[socks] in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.2.0b0) (2.32.3)
> Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.2.0b0                                                              ) (1.4.1)
> Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.2.0b0) (                                                              1.9.4)
> Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.2.0b0)                                                               (1.3.1)
> Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3                                                              .2.0b0) (2.3.5)
> Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3                                                              .2.0b0) (4.0.2)
> Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.2.0b0) (2                                                              3.1.0)
> Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloader==3.2.0                                                              b0) (6.0.5)
> Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.9/dist-packages (from yarl<2.0,>=1.0->aiohttp->yandex-music->yandex-music-downloader=                                                              =3.2.0b0) (3.7)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downloader                                                              ==3.2.0b0) (2024.6.2)
> Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-down                                                              loader==3.2.0b0) (3.3.2)
> Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downloader                                                              ==3.2.0b0) (2.2.1)
> Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-music-downlo                                                              ader==3.2.0b0) (1.7.1)
> Building wheels for collected packages: yandex-music-downloader
>   Building wheel for yandex-music-downloader (PEP 517) ... done
>   Created wheel for yandex-music-downloader: filename=yandex_music_downloader-3.2.0b0-py3-none-any.whl size=12344 sha256=5be28cab892a803fa464227914d9001                                                              5e1fce705ab17b06a30fbc6b4112ce7e5
>   Stored in directory: /tmp/pip-ephem-wheel-cache-5j3jf760/wheels/0b/f7/e3/b2601302bb26f4c39472a740b621d9743ccd557cc09557a3f0
> Successfully built yandex-music-downloader
> Installing collected packages: yandex-music-downloader
>   Attempting uninstall: yandex-music-downloader
>     Found existing installation: yandex-music-downloader 3.0.0b1
>     Uninstalling yandex-music-downloader-3.0.0b1:
>       Successfully uninstalled yandex-music-downloader-3.0.0b1
> Successfully installed yandex-music-downloader-3.2.0b0
> root@omv:~# yandex-music-downloader --quality 1 --add-lyrics --skip-existing --embed-cover --cover-resolution original --dir /mnt/musya --token "AgAAAAA                                                              CO3_rA-EtXkI3lLpFUQ" --url "https://music.yandex.ru/artist/1162253"
> Traceback (most recent call last):
>   File "/usr/local/bin/yandex-music-downloader", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/ymd/cli.py", line 260, in main
>     downloadable = core.to_downloadable_track(track, args.quality, save_path)
>   File "/usr/local/lib/python3.9/dist-packages/ymd/core.py", line 261, in to_downloadable_track
>     def sort_key(e: DownloadInfo) -> int | float:
> TypeError: unsupported operand type(s) for |: 'type' and 'type'
> root@omv:~# yandex-music-downloader --quality 1 --add-lyrics --skip-existing --embed-cover --cover-resolution 1000 --dir /mnt/musya --token "AgAAAAACO3_                                                              rAAG8I3lLpFFUQ" --url "https://music.yandex.ru/users/Druidblack/playlists/3"
> Traceback (most recent call last):
>   File "/usr/local/bin/yandex-music-downloader", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/ymd/cli.py", line 260, in main
>     downloadable = core.to_downloadable_track(track, args.quality, save_path)
>   File "/usr/local/lib/python3.9/dist-packages/ymd/core.py", line 261, in to_downloadable_track
>     def sort_key(e: DownloadInfo) -> int | float:
> TypeError: unsupported operand type(s) for |: 'type' and 'type'
> root@omv:~#
> 
```

**Comment by Druidblack** [comment]
Просьба. Можете сделать инструкцию, как можно откатится до предыдущей версии?
На случай если с обновление возникли проблемы.

**Comment by llistochek** [comment]
На вклалке Releases выберите нужную вам версию, скопируйте ссылку на Source code (zip) и передайте ее в `pip install`, например:
`https://github.com/llistochek/yandex-music-downloader/archive/refs/tags/v3.0.0b1.zip`

**Comment by llistochek** [comment]
Исправлено в c04415c08a312f788c6a55846c0cccdd4e64df69
