### ISSUE TITLE
Не работает версия 3.2.1 b0

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#78]
```
> 
> root@omv:~# pip install git+https://github.com/llistochek/yandex-music-downloader
> Collecting git+https://github.com/llistochek/yandex-music-downloader
>   Cloning https://github.com/llistochek/yandex-music-downloader to /tmp/pip-req-build-5fu4htkt
>   Running command git clone -q https://github.com/llistochek/yandex-music-downloader /tmp/pip-req-build-5                                                                                    fu4htkt
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>     Preparing wheel metadata ... done
> Requirement already satisfied: mutagen in /usr/lib/python3/dist-packages (from yandex-music-downloader==3.2.1b0) (1.45.1)
> Requirement already satisfied: yandex-music in /usr/local/lib/python3.9/dist-packages (from yandex-music-downloader==3.2.1b0) (2.2.0)
> Requirement already satisfied: aiohttp in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.2.1b0) (                                                     3.10.1)
> Requirement already satisfied: aiofiles in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.2.1b0)                                                      (22.1.0)
> Requirement already satisfied: requests[socks] in /usr/local/lib/python3.9/dist-packages (from yandex-music->yandex-music-downloader==3.                                                     2.1b0) (2.32.3)
> Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-d                                                     ownloader==3.2.1b0) (6.0.5)
> Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-mus                                                     ic-downloader==3.2.1b0) (2.3.5)
> Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downlo                                                     ader==3.2.1b0) (1.9.4)
> Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-dow                                                     nloader==3.2.1b0) (1.4.1)
> Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-mus                                                     ic-downloader==3.2.1b0) (4.0.2)
> Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-downloa                                                     der==3.2.1b0) (23.1.0)
> Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp->yandex-music->yandex-music-down                                                     loader==3.2.1b0) (1.3.1)
> Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.9/dist-packages (from yarl<2.0,>=1.0->aiohttp->yandex-music->yandex-m                                                     usic-downloader==3.2.1b0) (3.7)
> Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-                                                     music-downloader==3.2.1b0) (2024.6.2)
> Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->y                                                     andex-music-downloader==3.2.1b0) (3.3.2)
> Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yandex-                                                     music-downloader==3.2.1b0) (2.2.1)
> Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.9/dist-packages (from requests[socks]->yandex-music->yan                                                     dex-music-downloader==3.2.1b0) (1.7.1)
> root@omv:~# yandex-music-downloader --help
> Traceback (most recent call last):
>   File "/usr/local/bin/yandex-music-downloader", line 5, in <module>
>     from ymd.cli import main
>   File "/usr/local/lib/python3.9/dist-packages/ymd/cli.py", line 16, in <module>
>     from ymd import core
>   File "/usr/local/lib/python3.9/dist-packages/ymd/core.py", line 7, in <module>
>     from enum import Enum, StrEnum, auto
> ImportError: cannot import name 'StrEnum' from 'enum' (/usr/lib/python3.9/enum.py)
> 
```

**Comment by llistochek** [comment]
Исправлено в e8ab89cd7f70c5685d0e107b21a65e0ffb46f525. Спасибо за issue
