### ISSUE TITLE
Обработка сетевых ошибок

### ISSUE THREAD

**Issue by Druidblack** [llistochek/yandex-music-downloader#79]
Когда программа отрабатывает скачивание плейлиста, в конце часто выдает вот такую информацию. 

```
>  [MP3 320kbps] Загружается /mnt/musya/Smooth Jazz All Stars/Smooth Jazz All Stars Cover the Songs of Sade/13 - King of Sorrow.mp3
> [MP3 320kbps] Загружается /mnt/musya/Jonathan Fritzén/Diamonds/3 - Dance With Me.mp3
> [MP3 320kbps] Загружается /mnt/musya/Fury Weekend/Retro Rangers/4 - Stuck In The Sunshine.mp3
> Traceback (most recent call last):
>   File "/usr/local/bin/yandex-music-downloader", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/dist-packages/ymd/cli.py", line 264, in main
>     for track in result_tracks:
>   File "/usr/local/lib/python3.9/dist-packages/ymd/cli.py", line 259, in playlist_tracks_gen
>     yield track.fetch_track()
>   File "/usr/local/lib/python3.9/dist-packages/yandex_music/track_short.py", line 48, in fetch_track
>     return self.client.tracks(self.track_id)[0]
>   File "/usr/local/lib/python3.9/dist-packages/yandex_music/client.py", line 70, in wrapper
>     result = method(*args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/yandex_music/client.py", line 1962, in tracks
>     return self._get_list('track', track_ids, {'with-positions': str(with_positions)}, *args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/yandex_music/client.py", line 1899, in _get_list
>     result = self._request.post(url, params, *args, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/yandex_music/utils/request.py", line 284, in post
>     result = self._request_wrapper(
>   File "/usr/local/lib/python3.9/dist-packages/yandex_music/utils/request.py", line 242, in _request_wrapper
>     raise NetworkError(f'{message} ({resp.status_code}): {resp.content}')
> yandex_music.exceptions.NetworkError: Unknown HTTPError (500): b'upstream connect error or disconnect/reset before headers. reset reason: connection termination'
```

Обычно такое появляется когда я пробую скачивать плейлисты с большим количеством песен.

**Comment by llistochek** [comment]
Да, такое случается. Я добавлю функционал повторных запросов при сетевых ошибках

**Comment by dashke** [comment]
Давайте разберемся, у меня часто выскакивает ошибка так как трэков больше 4000.

**Comment by openssh-user** [comment]
Лично мне timeout не особо помогает. Пробовал выставлять timeout даже 300 секунд. Мне помогает только перезапуск всего процесса

**Comment by llistochek** [comment]
Реализовано в e435328907ff416bb65b3f248654283a26e7d921. Спасибо за issue
