### ISSUE TITLE
Ошибка при скачивании большого плейлиста.

### ISSUE THREAD

**Issue by Ruventium** [llistochek/yandex-music-downloader#81]
Как я понимаю из-за размера плейлиста происходит ошибка:

```
Трек 6/12 не доступен для скачивания
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ruventium\AppData\Local\Programs\Python\Python314\Scripts\yandex-music-downloader.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\Ruventium\AppData\Local\Programs\Python\Python314\Lib\site-packages\ymd\cli.py", line 269, in main
    save_path = args.dir / core.prepare_base_path(
                           ~~~~~~~~~~~~~~~~~~~~~~^
        args.path_pattern,
        ^^^^^^^^^^^^^^^^^^
        track,
        ^^^^^^
        args.unsafe_path,
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Ruventium\AppData\Local\Programs\Python\Python314\Lib\site-packages\ymd\core.py", line 77, in prepare_base_path
    artist = album.artists[0]
             ~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by llistochek** [comment]
Исправлено в f9cb171fef6184dd7aa7b3cfbf1327f2578a0261. Спасибо за issue
