### ISSUE TITLE
Некоторые недоступные треки остаются проигрываемыми в плейлистах и выдают ошибку при попытке получения их альбома

### ISSUE THREAD

**Issue by amythiz** [llistochek/yandex-music-downloader#84]
Странный глюк самой Яндекс Музыки, но мне встречается уже второй забагованный трек при попытках выкачать плейлист "Мне нравится". Трек недоступен, но проигрывается из самого плейлиста, у него нет обложки и в ссылке вообще нет альбома. Открытие самой ссылки на трек ведёт на страницу 404. Выглядят такие треки так:
![Снимок экрана 2024-12-01 194851](https://github.com/user-attachments/assets/c21fac9c-f198-46be-b7c9-73eabe1ffd9c)

Сама ошибка (я использую свой форк, поэтому номера строк могут отличаться):
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\psmir\AppData\Local\Programs\Python\Python313\Scripts\yandex-music-downloader.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\psmir\AppData\Local\Programs\Python\Python313\Lib\site-packages\ymd\cli.py", line 298, in main
    core.download_track(
    ~~~~~~~~~~~~~~~~~~~^
        track_info=downloadable,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        compatibility_level=args.compatibility_level,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\psmir\AppData\Local\Programs\Python\Python313\Lib\site-packages\ymd\core.py", line 234, in download_track
    album = track.albums[0]
            ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by llistochek** [comment]
Обновитесь до последней версии (#81)
