### ISSUE TITLE
Cкачивание треков с отсутствующей информацией об альбоме не было исправлено в v3.2.2b0

### ISSUE THREAD

**Issue by amythiz** [llistochek/yandex-music-downloader#85]
Ошибка исправлена в `prepare_base_path()`, но осталась в `download_track()`, где всё ещё есть `album = track.albums[0]` без проверки существования альбома.

**Comment by yezhoff** [comment]
Подтверждаю!

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python312\Scripts\yandex-music-downloader.exe\__main__.py", line 7, in <module>
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python312\Lib\site-packages\ymd\cli.py", line 291, in main
    core.download_track(
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python312\Lib\site-packages\ymd\core.py", line 250, in download_track
    album = track.albums[0]
            ~~~~~~~~~~~~^^^
IndexError: list index out of range

ответ api
"id": "100852367",
"realId": "100852367",
"title": "Geneva",
...
"albums": []

т.е. массив albums может быть пустым.
обложки тоже могут отсутствовать, но значение artists.cover.uri при это не пустое

{"id": "100852367", "realId": "100852367", "title": "Geneva", "major": {"id": 638, "name": "UGC"}, "available": true, "availableForPremiumUsers": true, "availableFullWithoutPermission": false, "availableForOptions": ["bookmate"], "disclaimers": [], "storageDir": "", "durationMs": 302860, "fileSize": 0, "r128": {"i": -9.56, "tp": -0.03}, "fade": {"inStart": 0, "inStop": 1.5, "outStart": 297.7, "outStop": 302.7}, "previewDurationMs": 30000, "artists": [{"id": 3280692, "name": "Superpoze", "various": false, "composer": false, "available": true, "cover": {"type": "from-album-cover", "uri": "avatars.yandex.net/get-music-content/5412783/19803973.a.19946593-1/%%", "prefix": "19803973.a.19946593-1"}, "genres": [], "disclaimers": []}], "albums": [], "lyricsAvailable": false, "type": "music", "rememberPosition": false, "trackSharingFlag": "COVER_ONLY", "lyricsInfo": {"hasAvailableSyncLyrics": false, "hasAvailableTextLyrics": false}, "trackSource": "OWN_REPLACED_TO_UGC", "prefix": ""}

**Comment by llistochek** [comment]
Исправлено. Спасибо за issue
